siteTitle="ui-manage docs"
baseColor = "#884499"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/inject/",
  "/docs/injectData/"
]
compPages = [
  "/examples/",
  "/examples/NeuTable/",
  "/examples/SearchWrapper/",
  "/examples/Link/",
  "/examples/Spinner/"
]
